;this file for FamiTone2 library generated by FamiStudio

_FinalTheme:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

.export _FinalTheme
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ;instrument 00 (Distortion Guitar)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Overdriven Guitar)
	.word @env1, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7f,$00,$00
@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80, $20, $8f, $20, $8d, $20, $8d
@song0ref11:
	.byte $34
@song0ref12:
	.byte $8f, $20, $8d, $20, $8d, $38, $8f, $20, $8d, $20, $8d, $3a, $8f, $38, $8d, $34, $8d, $20, $8f, $20, $8d, $20, $8d, $30
	.byte $8f, $20, $8d, $20, $8d, $30, $9f, $34, $8d, $00, $af, $38, $9f, $00, $f9, $99, $20, $83, $00, $20, $83, $00, $20, $8f
	.byte $20, $8d, $20, $8d, $2c, $af, $30, $af, $00, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
@song0ref80:
	.byte $00, $8f, $20, $8d, $20, $8d
@song0ref86:
	.byte $30, $9f, $34, $8d, $00, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $22, $af, $26, $af, $34, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
@song0ref124:
	.byte $22, $af, $30
@song0ref127:
	.byte $af, $00
@song0ref129:
	.byte $af, $2e, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $01
@song0ref141:
	.byte $20, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $01
@song0ref152:
	.byte $20, $af, $20, $8b, $01, $20, $89, $01, $20, $89
@song0ref162:
	.byte $01, $38, $8f, $34, $8d, $30, $8d, $34, $8f, $30, $8d, $2e, $8d
@song0ref175:
	.byte $20, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $01
@song0ref186:
	.byte $2e, $af, $20, $8b, $01, $20, $89, $01, $20, $89
@song0ref196:
	.byte $01, $2e, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $00, $e5
	.byte $ff, $16
	.word @song0ref175
	.byte $ff, $2d
	.word @song0ref152
	.byte $20, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $00, $e5, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $2c
@song0ref244:
	.byte $af, $26, $af, $26, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $11
	.word @song0ref124
	.byte $ff, $15
	.word @song0ref186
	.byte $ff, $2f
	.word @song0ref162
	.byte $ff, $20
	.word @song0ref175
	.byte $ff, $0d
	.word @song0ref162
	.byte $ff, $15
	.word @song0ref186
	.byte $ff, $0d
	.word @song0ref196
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f9, $f9, $e9, $80, $34, $af, $00, $f9, $f9, $e7, $26
@song0ref301:
	.byte $af, $00, $f9, $f9, $e7, $34, $af, $00, $f9, $f9, $f9, $9f, $f9, $f9, $e9, $34, $af, $00, $f9, $f9, $e7, $26
@song0ref323:
	.byte $af, $00, $f9, $f9, $f9, $9f, $f9, $f9, $b7, $26, $af, $24
	.byte $ff, $0c
	.word @song0ref323
	.byte $ff, $22
	.word @song0ref301
	.byte $ff, $0c
	.word @song0ref323
	.byte $af, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $82, $38, $9f, $00, $f9, $99, $20, $83, $00, $20, $83, $00, $2e, $8b, $01, $20, $89, $01, $20, $89, $01, $2e, $8f, $00
	.byte $9d
	.byte $ff, $0c
	.word @song0ref86
	.byte $ff, $13
	.word @song0ref11
	.byte $8b, $01, $20, $89, $01, $20, $89, $01, $22, $af, $26, $af, $00, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $22
	.byte $ff, $0c
	.word @song0ref244
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $2c, $af, $26
	.byte $ff, $24
	.word @song0ref127
	.byte $22, $af, $22, $af
	.byte $ff, $16
	.word @song0ref141
@song0ref436:
	.byte $2e
@song0ref437:
	.byte $af, $20, $8b, $01, $20, $89, $01, $20, $89, $01, $30, $af, $42, $af
	.byte $ff, $20
	.word @song0ref175
	.byte $01, $30, $af, $30, $af
	.byte $ff, $20
	.word @song0ref175
	.byte $01, $3e, $af, $34, $af, $20, $8f, $20, $8d, $20, $8d, $00
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $22
	.byte $ff, $0c
	.word @song0ref244
	.byte $ff, $17
	.word @song0ref12
	.byte $ff, $13
	.word @song0ref80
	.byte $ff, $17
	.word @song0ref12
	.byte $22, $af, $30, $af, $00, $af
	.byte $ff, $16
	.word @song0ref175
@song0ref505:
	.byte $20, $af, $20, $8b, $01, $20, $89, $01, $20, $89, $01, $22, $af, $30
	.byte $ff, $17
	.word @song0ref129
	.byte $ff, $0f
	.word @song0ref436
	.byte $ff, $16
	.word @song0ref175
	.byte $ff, $0d
	.word @song0ref505
	.byte $22, $af
	.byte $ff, $16
	.word @song0ref141
	.byte $20
	.byte $ff, $0c
	.word @song0ref437
	.byte $34, $af, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref546:
	.byte $f9, $f9, $f9, $a1, $f9, $f9, $f9, $a1, $f9, $f9, $f9, $a1
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $ff, $0c
	.word @song0ref546
	.byte $fd
	.word @song0ch4loop
